---
security:
  ignore-vulnerabilities:
    51457:
      reason: SVN isn't used by this project
    70612:
      reason: Agree with `jinja2` maintainers, we shouldn't (and aren't) rendering random templates
