---
name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    name: "${{ matrix.session }} ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python-version: 3.9, session: "tests" }

    env:
      NOXSESSION: "${{ matrix.session }}"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.3.4

      - name: Set up Python "${{ matrix.python-version }}"
        uses: actions/setup-python@v2.2.1
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version

      - name: Install Poetry
        run: |
          pip install --constraint=.github/workflows/constraints.txt poetry
          poetry --version

      - name: Build packages
        if: matrix.session == 'tests'
        run: |
          poetry build --ansi

      - name: Upload packages
        if: matrix.session == 'tests' && matrix.python-version == '3.9'
        uses: "actions/upload-artifact@v2.2.2"
        with:
          name: packages
          path: "dist/"

  rpmbuild:
    runs-on: ubuntu-18.04
    needs: tests
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.3.4

      - name: Download packages
        uses: actions/download-artifact@v2.0.8
        with:
          name: packages

      - name: Setup mock
        run: |
          sudo apt-get update
          sudo apt-get install -y mock
          sudo usermod -a -G mock $(whoami)

      - name: Initialize mock chroot
          mock -r epel-7-x86_64 --init
          ls dist/
